name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore CnbExchangeRateProvider.sln
      - name: Build
        run: dotnet build --no-restore --configuration Release CnbExchangeRateProvider.sln
      - name: Test
        run: dotnet test --no-build --configuration Release CnbExchangeRateProvider.sln
  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: |
          docker build -t exchange-rate-updater-api:ci -f ExchangeRateUpdater.Api/Dockerfile .
      - name: Build Console image
        run: |
          docker build -t exchange-rate-updater-console:ci -f ExchangeRateUpdater.Console/Dockerfile .


